import os
env = Environment(ENV = os.environ)

if env['PLATFORM'] == 'win32':
	env.Append(
		CPPDEFINES = ['/DWIN32', '/D_WIN32'], 
		CXXFLAGS = ['/W3', '/EHsc', '/wd4996'], 
		CPPPATH = [], 
		LIBPATH = [])

	# If you are using VC++ 8.0, you probably need to install the 
	# Microsoft Platform SDK and uncomment the following.
	#env.Append(CPPPATH = ['C:\Program Files\Microsoft Platform SDK\Include'])
	#env.Append(LIBPATH = ['C:\Program Files\Microsoft Platform SDK\Lib'])

env.Program('test', source = ['test.cpp'])
